hackathon-group-4/Hackathon.N00BS.FormularioMvc2/Controllers/CorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace Hackathon.N00BS.FormularioMvc2.Controllers
{
    public class CorController : Controller
    {
        // GET: Cor
        public ActionResult Index()
        {
            
            
            string x = new FacilitadorWebApi("RetornarTodas", "Cores").Disparar();

            var cores = new JavaScriptSerializer().Deserialize<List<string>>(x);

            ViewBag.Cores = cores;

            return View();
        }
    }
}

hackathon-group-4/Hackathon.N00BS.FormularioMvc2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hackathon.N00BS.FormularioMvc2.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

hackathon-group-4/Hackathon.N00BS.FormularioMvc2/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace Hackathon.N00BS.FormularioMvc2.Controllers
{
    public class ProdutoController : Controller
    {
        // GET: Produto
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Salvar(Comum.ProdutoModel modelo) 
        {
            var produtos = new List<Comum.ProdutoModel>();
            {
                new Comum.ProdutoModel
                {
                    CodigoBarras = modelo.CodigoBarras,
                    Cor = modelo.Cor,
                    Descricao = modelo.Descricao,
                    Marca = modelo.Marca,
                    Modelo = modelo.Modelo,
                    Preco = modelo.Preco,
                    Tamanho = modelo.Tamanho,
                    Data = DateTime.Now
                };
            };

            WebRequest webRequest = WebRequest.Create("http://localhost:50205/api/Produtos/Gravar");
            webRequest.Method = "POST";
            webRequest.ContentType = "application/json";

            string jsonParaEnvio = new JavaScriptSerializer().Serialize(produtos);

            using (StreamWriter streamWriter = new StreamWriter(webRequest.GetRequestStream()))
            {
                streamWriter.Write(jsonParaEnvio);
                streamWriter.Flush();
                streamWriter.Close();

                HttpWebResponse response = (HttpWebResponse)webRequest.GetResponse();

                using (StreamReader streamReader = new StreamReader(response.GetResponseStream()))
                {
                    var resultado = streamReader.ReadToEnd();
                }
            }

            return View();
        }

        public ActionResult ListarBons() 
        {
            string retorno = new FacilitadorWebApi("RetornarTodosBons", "Produtos").Disparar();

            var bons = new JavaScriptSerializer().Deserialize<List<Comum.ProdutoModel>>(retorno);

            ViewBag.Bons = bons;

            return View();
        }

        public ActionResult ListarRuins() 
        {
            string retorno = new FacilitadorWebApi("RetornarTodosRuins", "Produtos").Disparar();

            var ruins = new JavaScriptSerializer().Deserialize<List<Comum.ProdutoModel>>(retorno);

            ViewBag.Bons = ruins;

            return View();
        }
    }
}

hackathon-group-4/Hackathon.N00BS.FormularioMvc2/Views/Cor/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Template/_LayoutPage1.cshtml";
}

<h2>Cores REAIS Netshoes</h2>

<table class="table table-hover table-striped">
    <thead>
        <tr>
            <td>Cores</td>
        </tr>
    </thead>
    <tbody>
        @foreach (string cor in ViewBag.Cores)
        {
            <tr>
                <td>@cor</td>
            </tr>
        }
    </tbody>
</table>

hackathon-group-4/Hackathon.N00BS.FormularioMvc2/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Template/_LayoutPage1.cshtml";
}

<h2>Pagina Inicial</h2>

<div class="text-center">
    <img src="~/WhatsApp Image 2019-09-29 at 05.53.49.jpeg" />
</div>

hackathon-group-4/Hackathon.N00BS.FormularioMvc2/Views/Produto/Index.cshtml
@model Hackathon.N00BS.Comum.ProdutoModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Template/_LayoutPage1.cshtml";
}

<h2>Index</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Novo Produto Mkt Place</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CodigoBarras, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CodigoBarras, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CodigoBarras, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Marca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Modelo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Modelo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Modelo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tamanho, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tamanho, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tamanho, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Data, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Inserir" class="btn btn-primary" formmethod="post" formaction="Salvar" />
            </div>
        </div>
    </div>
}

hackathon-group-4/Hackathon.N00BS.FormularioMvc2/Views/Produto/ListarBons.cshtml
@{
    ViewBag.Title = "ListarBons";
    Layout = "~/Views/Template/_LayoutPage1.cshtml";
}

<h2>Dados bons</h2>

<table class="table table-hover table-striped">
    <thead>
        <tr>
            <th>Codigo de Barras</th><th>Cor</th><th>Data Cadastro</th>
        </tr>
    </thead>
    <tbody>
        @foreach (string produto in ViewBag.Bons)
        {
        <tr>
            <td>@produto.CodigoBarras</td>
            <td>@produto.Cor</td>
            <td>@produto.Data</td>
        </tr>
        }
    </tbody>
</table>

hackathon-group-4/Hackathon.N00BS.FormularioMvc2/Views/Template/_LayoutPage1.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Estilo/bootstrap-4.3.1-dist/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Estilo/jquery-3.4.1.min.js"></script>
    <script src="~/Estilo/bootstrap-4.3.1-dist/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container-fluid">
        <div class="menu" style="background-color:darkslateblue">
            <ul class="nav">
                <li class="nav-item">
                    @Html.ActionLink("Inserir Produto", "Inserir", "Produto", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Listar Produto Bons", "Index", "Produto", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Listar Produto Ruins", "Index", "Produto", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Cores", "Index", "Cor", null, new { @class = "nav-link" })
                </li>
            </ul>
        </div>
        @RenderBody()
    </div>
</body>
</html>